### ISSUE TITLE
Fleur/miel Kernel OpenSource code

### ISSUE THREAD

**Issue by charansoma3001** [ivan19871002/xiaomi_local_manifest#1]
Hi @ivan19871002 ,
I request on behalf of the entire fleur/miel (Poco M4 Pro 4g/Redmi Note 11S 4G) community to release fleur/miel (Poco M4 Pro 4g/Redmi Note 11S 4G) Kernel OpenSource code, please, we beg you!
![Screenshot 2023-01-11 124044](https://user-images.githubusercontent.com/55019184/211741544-22231cdd-6bc5-4542-ae0d-124deda805ea.png)

**Comment by ivan19871002** [comment]
I have left Xiaomi company   2022.2
